# utils/gist.py
import requests
import json

def create_gist(code, description="Generated by AI Coding Genius"):
    url = "https://api.github.com/gists"
    headers = {"Authorization": "token YOUR_GITHUB_TOKEN"}  # User would add
    data = {
        "description": description,
        "public": True,
        "files": {
            "main.py": {"content": code}
        }
    }
    response = requests.post(url, headers=headers, data=json.dumps(data))
    return response.json().get("html_url", "Failed")
